name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "lldpwr/hierarchy:$GITHUB_SHA" \
          .

    # Merge to release
    - name: Merge main -> releases
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        target_branch: releases
        github_token: ${{ github.token }}


