name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  setup-build:
    name: Setup, Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "lldpwr/hierarchy:$GITHUB_SHA" \
          .



